name: Vite with Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.15.0']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2

      - name: Install package and Build 🔧
        run: |
          pnpm install

      - name: Build 🔧
        run: |
          pnpm run build
          cp dist/index.html dist/404.html # vue-router history mode

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          # folder dist/* -> branch gh-pages /
          branch: gh-pages
          folder: dist
